const Footer = () => {
    return (
        <div className="bg-[#ceece6] h-auto flex">

            <div className="w-1/3">
                <div className="m-20">Disclaimer : The predictions generated by this model are estimates and should not be interpreted as definitive or conclusive. Always consult a healthcare professional for proper diagnosis and treatment.</div>
            </div>

            <div className="h-auto bg-white w-1 mt-8 mb-8"></div>

            <div className="flex flex-col space-y-4 items-center justify-center ml-8 w-1/3">

                <label for="message" class="block mb-2 text-2xl font-medium  text-[#1b1818]" >Any Queries ?</label>
                <textarea id="message" rows="4" className=" block w-full mr-5 text-sm text-white bg-[#292525] rounded-lg border ring-[#1b1818] border-[#1b1818]  placeholder-gray-400 " placeholder="Leave a comment..."></textarea>

                <button href="#" target="blank" className=" mt-10 relative inline-flex items-center px-12 py-3 overflow-hidden text-lg font-medium text-black border-2 border-[#77d5ca] rounded-full hover:text-white group hover:bg-[#77d5ca]">
                    <span className="absolute left-0 block w-full h-0 transition-all bg-[#77d5ca] opacity-100 group-hover:h-full top-1/2 group-hover:top-0 duration-400 ease"></span>
                    <span className="absolute right-0 flex items-center justify-start w-10 h-10 duration-300 transform translate-x-full group-hover:translate-x-0 ease">
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path></svg>
                    </span>
                    <span className="relative">Submit</span>
                </button>
            </div>

            <div className="h-auto bg-white w-1 mt-8 mb-8"></div>

            <div className="w-1/3">
                <ul className="ml-5 mt-12 space-y-4 text-xl">
                    <li>
                        <a href="#">About Us</a>
                    </li>
                    <li>
                        <a href="#">Carrers</a>
                    </li>
                    <li>
                        <a href="#">News And Media</a>
                    </li>
                    <li>
                        <a href="#">Connect</a>
                    </li>
                </ul>
            </div>

        </div>
    )
}
export default Footer;